// This file is auto-generated by Supabase CLI.
// Run `npm run db:types` after connecting to your Supabase project to regenerate.
// DO NOT edit manually.

// Placeholder until Supabase project is connected.
// All queries should use the domain types in domain.ts for now.

export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string | null
          primary_color: string
          twilio_number: string | null
          stripe_account_id: string | null
          plan_tier: string
          after_hours_fee_cents: number
          after_hours_start: string
          after_hours_end: string
          highway_minimum_fee_cents: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          logo_url?: string | null
          primary_color?: string
          twilio_number?: string | null
          stripe_account_id?: string | null
          plan_tier?: string
          after_hours_fee_cents?: number
          after_hours_start?: string
          after_hours_end?: string
          highway_minimum_fee_cents?: number
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          logo_url?: string | null
          primary_color?: string
          twilio_number?: string | null
          stripe_account_id?: string | null
          plan_tier?: string
          after_hours_fee_cents?: number
          after_hours_start?: string
          after_hours_end?: string
          highway_minimum_fee_cents?: number
          created_at?: string
        }
      }
      users: {
        Row: {
          id: string
          tenant_id: string
          role: string
          name: string
          phone: string | null
          email: string | null
          avatar_url: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id: string
          tenant_id: string
          role: string
          name: string
          phone?: string | null
          email?: string | null
          avatar_url?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          role?: string
          name?: string
          phone?: string | null
          email?: string | null
          avatar_url?: string | null
          is_active?: boolean
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: {
      get_user_tenant_id: {
        Args: Record<string, never>
        Returns: string
      }
      get_user_role: {
        Args: Record<string, never>
        Returns: string
      }
    }
    Enums: Record<string, never>
  }
}
